---
- name: Continuous Integration
  hosts: localhost

  tasks:

    - name: Code Quality
      shell: echo "Performing Code Quality Check"
      register: t1
    - debug:
        var: t1.stdout_lines

    - name: Unit Test & Cov
      shell: echo "Performing Code Coverage and Unit Test"
      register: t2
    - debug:
        var: t2.stdout_lines

    - name: Unit NFT
      shell: echo "Performing unit NFT"
      register: t3
    - debug:
        var: t3.stdout_lines

    - name: SAST
      shell: echo "Performing STAT"
      register: t4
    - debug:
        var: t4.stdout_lines

    - name: Build Packages
      shell: echo "Building and Signing Packages"
      register: t5
    - debug:
        var: t5.stdout_lines
